name: "Build"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  BuildMac:
    runs-on: "macos-13"

    strategy:
      matrix:
        config:
          - "Release"

    steps:
      - name: "Get version"
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: "actions/checkout@v4"

      - name: "Run CT2 build"
        run: "./build_ct2_macos.sh ${{ matrix.config }}  ${{ steps.get-version.outputs.version }}"

      - name: "Run SP build"
        run: "./build_sp_macos.sh ${{ matrix.config }}  ${{ steps.get-version.outputs.version }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libraries-macos-${{ matrix.config }}-${{ steps.get-version.outputs.version }}"
          path: "dist/*.tar.gz"

  BuildLinux:
    if: false
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        config:
          - "Debug"
          - "Release"

    steps:
      - name: "Get version"
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Run build-linux.sh"
        run: "./build-linux.sh ${{ matrix.config }} ${{ steps.get-version.outputs.version }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libcurl-linux-${{ matrix.config }}"
          path: "dist/*.tar.gz"

  BuildWindows:
    runs-on: "windows-2022"

    strategy:
      matrix:
        config:
          - "Release"
        cuda: [ 'cpu', '12.2.0', '11.8.0' ]

    steps:
      - name: "Get version"
        shell: bash
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: Jimver/cuda-toolkit@v0.2.14
        if: matrix.cuda != 'cpu'
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}
          method: 'local'

      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Run Build CT2 Windows ps1"
        run: "./build_ct2_windows.ps1 -Configuration ${{ matrix.config }} -CudaVersionOrCpu ${{ matrix.cuda }}"

      - name: "Run Build SP Windows ps1"
        run: "./build_sp_windows.ps1 -Configuration ${{ matrix.config }}"

      - name: Setup filename
        shell: pwsh
        run: |
          if ("${{ matrix.cuda }}" -eq 'cpu') {
            echo "FILENAME=cpu" >> $Env:GITHUB_ENV
          } else {
            echo "FILENAME=cuda${{ matrix.cuda }}" >> $Env:GITHUB_ENV
          }

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libctranslate2-windows-${{ matrix.config }}-$Env:FILENAME"
          path: "dist/*.zip"

  Release:
    runs-on: "ubuntu-22.04"
    if: "github.event_name == 'push' && contains(github.ref, 'refs/tags/')"
    needs: [BuildMac, BuildWindows] #TODO: BuildLinux
    permissions:
      contents: "write"
    defaults:
      run:
        shell: bash
    steps:
      - name: "Get Metadata"
        id: "metadata"
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: "Download build artifacts"
        uses: "actions/download-artifact@v4"

      - name: Generate Checksums 🪪
        run: |
          : Generate Checksums 🪪
          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
          shopt -s extglob

          echo "### Checksums" > ${{ github.workspace }}/CHECKSUMS.txt
          for file in $( find ${{ github.workspace }} -name "*.tar.gz" -o -name "*.zip" ); do
            echo "    ${file##*/}: $(sha256sum "${file}" | cut -d " " -f 1)" >> ${{ github.workspace }}/CHECKSUMS.txt
          done

      - name: "Create Release"
        uses: "softprops/action-gh-release@v2"
        with:
          draft: true
          tag_name: "${{ steps.metadata.outputs.version }}"
          name: "${{ steps.metadata.outputs.version }}"
          body_path: ${{ github.workspace }}/CHECKSUMS.txt
          files: |
            ${{ github.workspace }}/**/*.tar.gz
            ${{ github.workspace }}/**/*.zip
